services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rentloop-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_strong_Passw0rd!
      - MSSQL_MEMORY_LIMIT_MB=1024
    ports:
      - "14330:1433"
    volumes:
      - rentloop_sql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rentloop-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

  api:
    build:
      context: .
      dockerfile: RentLoop.API/Dockerfile
    container_name: rentloop-api
    ports:
      - "5068:8080"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=220073;User Id=sa;Password=Your_strong_Passw0rd!;TrustServerCertificate=True;Encrypt=False;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=guest
      - RabbitMQ__Pass=guest
      - Jwt__Key=RentLoopSuperSecretKey_1234567890_ABCDEF
      - Jwt__Issuer=RentLoop
      - Jwt__Audience=RentLoop
      - Jwt__ExpiresMinutes=60
      - PayPal__Mode=sandbox
      - PayPal__ClientId=AVEbddT2dPQCBQ6jYeRwHs8OnXDC9Tire9aaKUXgOCMaxN9rpNRO_wen1-_xROJwGP4pA9TcRZlu-w2K
      - PayPal__ClientSecret=EOudUv7tEquT2p9gR_OcZhbb3Gxk2-KAP0zXZSX8uT8Se_q4FEeYcg63ddadgxFowZfdRy6mp3OClMT_
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: RentLoop.Worker/Dockerfile
    container_name: rentloop-worker
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__User=guest
      - RabbitMQ__Pass=guest
      - ConnectionStrings__DefaultConnection=Server=db;Database=220073;User Id=sa;Password=Your_strong_Passw0rd!;TrustServerCertificate=True;Encrypt=False;
    restart: on-failure

volumes:
  rentloop_sql_data: