// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentLoop.API.Data;

#nullable disable

namespace RentLoop.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260114210351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentLoop.API.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Klima"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lift"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Balkon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pogled"
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Banja Luka"
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("RentLoop.API.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId", "PropertyId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("RentLoop.API.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DistanceToCenterKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxGuests")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RoomsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RentTypeId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kneza Domagoja 12",
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Moderan studio blizu Starog mosta. Idealan za parove i kratki boravak.",
                            DistanceToCenterKm = 0.60m,
                            HasAirConditioning = true,
                            HasWifi = true,
                            IsActive = true,
                            MaxGuests = 2,
                            Name = "Sunset Studio – Centar Mostara",
                            PetsAllowed = false,
                            PricePerNight = 85.00m,
                            RentTypeId = 1,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Maršala Tita 44",
                            CityId = 1,
                            CreatedAt = new DateTime(2025, 1, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Svijetao apartman s pogledom, mirna zgrada, odlična lokacija.",
                            DistanceToCenterKm = 1.20m,
                            HasAirConditioning = false,
                            HasWifi = true,
                            IsActive = true,
                            MaxGuests = 4,
                            Name = "Neretva View Apartment",
                            PetsAllowed = true,
                            PricePerNight = 110.00m,
                            RentTypeId = 1,
                            RoomsCount = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Zelenih beretki 7",
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "U srcu starog grada – sve je na pješačkoj udaljenosti. Toplo i udobno.",
                            DistanceToCenterKm = 0.30m,
                            HasAirConditioning = true,
                            HasWifi = true,
                            IsActive = true,
                            MaxGuests = 3,
                            Name = "Baščaršija Cozy Stay",
                            PetsAllowed = false,
                            PricePerNight = 95.00m,
                            RentTypeId = 1,
                            RoomsCount = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hamdije Kreševljakovića 18",
                            CityId = 2,
                            CreatedAt = new DateTime(2025, 1, 18, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Praktičan stan za duži boravak, dobar prevoz i mirna lokacija.",
                            DistanceToCenterKm = 1.00m,
                            HasAirConditioning = false,
                            HasWifi = true,
                            IsActive = true,
                            MaxGuests = 4,
                            Name = "Business Flat – Sarajevo Center",
                            PetsAllowed = true,
                            PricePerNight = 60.00m,
                            RentTypeId = 2,
                            RoomsCount = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "Slatina 21",
                            CityId = 3,
                            CreatedAt = new DateTime(2025, 1, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prostran stan za porodice, mirno naselje, blizina prodavnica i parka.",
                            DistanceToCenterKm = 1.80m,
                            HasAirConditioning = true,
                            HasWifi = true,
                            IsActive = true,
                            MaxGuests = 6,
                            Name = "Tuzla Family Comfort",
                            PetsAllowed = true,
                            PricePerNight = 75.00m,
                            RentTypeId = 1,
                            RoomsCount = 3
                        },
                        new
                        {
                            Id = 6,
                            Address = "Kralja Petra I 9",
                            CityId = 4,
                            CreatedAt = new DateTime(2025, 1, 22, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minimalistički loft, čist dizajn, idealan za city break.",
                            DistanceToCenterKm = 0.90m,
                            HasAirConditioning = true,
                            HasWifi = true,
                            IsActive = true,
                            MaxGuests = 2,
                            Name = "Banja Luka Minimal Loft",
                            PetsAllowed = false,
                            PricePerNight = 88.00m,
                            RentTypeId = 1,
                            RoomsCount = 1
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.ListingView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("ListingViews");
                });

            modelBuilder.Entity("RentLoop.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RentLoop.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("RelatedPropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedPropertyId");

                    b.HasIndex("RelatedReservationId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("RentLoop.API.Models.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PriceDrop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ReservationApproved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ReservationRejected"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reminder"
                        },
                        new
                        {
                            Id = 5,
                            Name = "General"
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RentLoop.API.Models.PropertyAmenity", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("PropertyId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PropertyAmenities");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 1,
                            AmenityId = 3
                        },
                        new
                        {
                            PropertyId = 1,
                            AmenityId = 5
                        },
                        new
                        {
                            PropertyId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 2,
                            AmenityId = 2
                        },
                        new
                        {
                            PropertyId = 2,
                            AmenityId = 6
                        },
                        new
                        {
                            PropertyId = 3,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 3,
                            AmenityId = 4
                        },
                        new
                        {
                            PropertyId = 3,
                            AmenityId = 6
                        },
                        new
                        {
                            PropertyId = 4,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 4,
                            AmenityId = 2
                        },
                        new
                        {
                            PropertyId = 5,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 5,
                            AmenityId = 2
                        },
                        new
                        {
                            PropertyId = 5,
                            AmenityId = 5
                        },
                        new
                        {
                            PropertyId = 6,
                            AmenityId = 1
                        },
                        new
                        {
                            PropertyId = 6,
                            AmenityId = 3
                        },
                        new
                        {
                            PropertyId = 6,
                            AmenityId = 6
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.PropertyAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("PropertyId", "Date")
                        .IsUnique();

                    b.ToTable("PropertyAvailability");
                });

            modelBuilder.Entity("RentLoop.API.Models.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCover")
                        .HasColumnType("bit");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCover = true,
                            PropertyId = 1,
                            SortOrder = 0,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2018/04/Pinterest-sadf-930x697.jpg?x60971"
                        },
                        new
                        {
                            Id = 2,
                            IsCover = false,
                            PropertyId = 1,
                            SortOrder = 1,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwFAeh2TrHWJ__9LhnRz4cYa5xWmJc_7GQEw&s"
                        },
                        new
                        {
                            Id = 3,
                            IsCover = false,
                            PropertyId = 1,
                            SortOrder = 2,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7hkXlEgH4y-vRg38k0I6XjZoWZmI5z813Dw&s"
                        },
                        new
                        {
                            Id = 4,
                            IsCover = true,
                            PropertyId = 2,
                            SortOrder = 0,
                            Url = "https://www.mojstan.net/wp-content/uploads/2014/11/simpatican-stan-povrsine-40-kvadrata-2.jpg"
                        },
                        new
                        {
                            Id = 5,
                            IsCover = false,
                            PropertyId = 2,
                            SortOrder = 1,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7hkXlEgH4y-vRg38k0I6XjZoWZmI5z813Dw&s"
                        },
                        new
                        {
                            Id = 6,
                            IsCover = false,
                            PropertyId = 2,
                            SortOrder = 2,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2018/12/Mali-stan-Moskva-15-e1544544438756-930x615.jpg?x60971"
                        },
                        new
                        {
                            Id = 7,
                            IsCover = true,
                            PropertyId = 3,
                            SortOrder = 0,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2018/12/Mali-stan-Moskva-15-e1544544438756-930x615.jpg?x60971"
                        },
                        new
                        {
                            Id = 8,
                            IsCover = false,
                            PropertyId = 3,
                            SortOrder = 1,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2021/06/Divan-mali-stan-za-najam.jpg-11-930x697.jpg?x60971"
                        },
                        new
                        {
                            Id = 9,
                            IsCover = false,
                            PropertyId = 3,
                            SortOrder = 2,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2021/06/Divan-mali-stan-za-najam.jpg-11-930x697.jpg?x60971"
                        },
                        new
                        {
                            Id = 10,
                            IsCover = true,
                            PropertyId = 4,
                            SortOrder = 0,
                            Url = "https://www.kucastil.rs/uploads/ck_editor/images/clanci/ENTERIJER/Sjajna%20re%C5%A1enja%20za%20stanove%20do%2040%20m%C2%B2%20DETALJAN%20PLAN/Sjajna%20re%C5%A1enja%20za%20stanove%20do%2040%20m%C2%B2%20ll%20(6).jpg"
                        },
                        new
                        {
                            Id = 11,
                            IsCover = false,
                            PropertyId = 4,
                            SortOrder = 1,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgcC_TwoxChv1vFapfVryyw7qT009JC-oLtw&s"
                        },
                        new
                        {
                            Id = 12,
                            IsCover = false,
                            PropertyId = 4,
                            SortOrder = 2,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2021/06/Divan-mali-stan-za-najam.jpg-11-930x697.jpg?x60971"
                        },
                        new
                        {
                            Id = 13,
                            IsCover = true,
                            PropertyId = 5,
                            SortOrder = 0,
                            Url = "https://www.mojstan.net/wp-content/uploads/2013/12/kreativni-stan-od-40-m2-2.jpg"
                        },
                        new
                        {
                            Id = 14,
                            IsCover = false,
                            PropertyId = 5,
                            SortOrder = 1,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgcC_TwoxChv1vFapfVryyw7qT009JC-oLtw&s"
                        },
                        new
                        {
                            Id = 15,
                            IsCover = false,
                            PropertyId = 5,
                            SortOrder = 2,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2021/06/Divan-mali-stan-za-najam.jpg-11-930x697.jpg?x60971"
                        },
                        new
                        {
                            Id = 16,
                            IsCover = true,
                            PropertyId = 6,
                            SortOrder = 0,
                            Url = "https://www.mojstan.net/wp-content/uploads/2013/12/kreativni-stan-od-40-m2-2.jpg"
                        },
                        new
                        {
                            Id = 17,
                            IsCover = false,
                            PropertyId = 6,
                            SortOrder = 1,
                            Url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgcC_TwoxChv1vFapfVryyw7qT009JC-oLtw&s"
                        },
                        new
                        {
                            Id = 18,
                            IsCover = false,
                            PropertyId = 6,
                            SortOrder = 2,
                            Url = "https://dupqmgrdwnev6.cloudfront.net/wp-content/uploads/2021/06/Divan-mali-stan-za-najam.jpg-11-930x697.jpg?x60971"
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.RentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ShortTerm"
                        },
                        new
                        {
                            Id = 2,
                            Name = "LongTerm"
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByAdminId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RentLoop.API.Models.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RentLoop.API.Models.SearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("Guests")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("RentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchHistory");
                });

            modelBuilder.Entity("RentLoop.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Mostar",
                            Email = "admin@rentloop.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "RentLoop",
                            PasswordHash = "AQAAAAIAAYagAAAAEMRw5vgxTMvW08zOCvCTMu4hHp1VPdxSFwkFUDbdOiwMo/GAwIDM/EKFwr7tHuGfQQ==",
                            Phone = "000-000",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sarajevo",
                            Email = "demo@rentloop.com",
                            FirstName = "Demo",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEM3ETeA/RYamGNigPexLLY0+LFq45A7YNMIh3Z33DDbie/i4U5DyIsN9QYL+G+aycA==",
                            Phone = "061-111-222",
                            Role = 0,
                            Username = "demo"
                        });
                });

            modelBuilder.Entity("RentLoop.API.Models.Conversation", b =>
                {
                    b.HasOne("RentLoop.API.Models.User", "Admin")
                        .WithMany("AdminConversations")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany("ClientConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.Favorite", b =>
                {
                    b.HasOne("RentLoop.API.Models.Listing", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.Listing", b =>
                {
                    b.HasOne("RentLoop.API.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.RentType", "RentType")
                        .WithMany("Properties")
                        .HasForeignKey("RentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("RentType");
                });

            modelBuilder.Entity("RentLoop.API.Models.ListingView", b =>
                {
                    b.HasOne("RentLoop.API.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany("ListingViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.Message", b =>
                {
                    b.HasOne("RentLoop.API.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.User", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("RentLoop.API.Models.Notification", b =>
                {
                    b.HasOne("RentLoop.API.Models.Listing", "RelatedProperty")
                        .WithMany()
                        .HasForeignKey("RelatedPropertyId");

                    b.HasOne("RentLoop.API.Models.Reservation", "RelatedReservation")
                        .WithMany()
                        .HasForeignKey("RelatedReservationId");

                    b.HasOne("RentLoop.API.Models.NotificationType", "Type")
                        .WithMany("Notifications")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedProperty");

                    b.Navigation("RelatedReservation");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.Payment", b =>
                {
                    b.HasOne("RentLoop.API.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.PropertyAmenity", b =>
                {
                    b.HasOne("RentLoop.API.Models.Amenity", "Amenity")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.Listing", "Property")
                        .WithMany("PropertyAmenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RentLoop.API.Models.PropertyAvailability", b =>
                {
                    b.HasOne("RentLoop.API.Models.Listing", "Property")
                        .WithMany("Availability")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.Reservation", "Reservation")
                        .WithMany("BookedDays")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Property");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("RentLoop.API.Models.PropertyImage", b =>
                {
                    b.HasOne("RentLoop.API.Models.Listing", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RentLoop.API.Models.Reservation", b =>
                {
                    b.HasOne("RentLoop.API.Models.User", "ApprovedByAdmin")
                        .WithMany()
                        .HasForeignKey("ApprovedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RentLoop.API.Models.Listing", "Property")
                        .WithMany("Reservations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.ReservationStatus", "Status")
                        .WithMany("Reservations")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("Property");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.Review", b =>
                {
                    b.HasOne("RentLoop.API.Models.Listing", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.Reservation", "Reservation")
                        .WithOne("Review")
                        .HasForeignKey("RentLoop.API.Models.Review", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.SearchHistory", b =>
                {
                    b.HasOne("RentLoop.API.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("RentLoop.API.Models.RentType", "RentType")
                        .WithMany()
                        .HasForeignKey("RentTypeId");

                    b.HasOne("RentLoop.API.Models.User", "User")
                        .WithMany("Searches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("RentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentLoop.API.Models.Amenity", b =>
                {
                    b.Navigation("PropertyAmenities");
                });

            modelBuilder.Entity("RentLoop.API.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RentLoop.API.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("RentLoop.API.Models.Listing", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("PropertyAmenities");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RentLoop.API.Models.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("RentLoop.API.Models.RentType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RentLoop.API.Models.Reservation", b =>
                {
                    b.Navigation("BookedDays");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("RentLoop.API.Models.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RentLoop.API.Models.User", b =>
                {
                    b.Navigation("AdminConversations");

                    b.Navigation("ClientConversations");

                    b.Navigation("Favorites");

                    b.Navigation("ListingViews");

                    b.Navigation("Notifications");

                    b.Navigation("Reservations");

                    b.Navigation("Searches");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
